global:
  scrape_interval: 30s

rule_files:
  - rules.yml

scrape_configs:
  - job_name: my_server
    scrape_interval: 10s
    static_configs:
      - targets:
        - prometheus:9090
        - host.docker.internal:9100